### ISSUE TITLE
pypicloud: access related question

### ISSUE THREAD

**Issue by kirankotari** [simjay/pypi-demo#1]
Hi Jaehyun,

I am exploring pypicloud and got a chance to look your video from "The Linux Foundation", here my question goes
When I create/register a new user he/she doesn't have a capability to upload or view any libraries in pypicloud.

Can you suggest how to create users which are not admin and provide default read access, upload access. Is this possible? 

Thanks in advance, 
Kiran Kumar K

**Comment by kirankotari** [comment]
@simjay Got it, never mind. 
I can setup following group by default
```
pypi.default_read = admin
pypi.default_write = admin
```

**Comment by simjay** [comment]
sorry for the late response. Glad you figured out :)
